version: 0.1

phases:
  pre_build:
    commands:
      - echo hello pre_build!
      - docker build -t hello-ci-cd .
  build:
    commands:
      - docker-compose
      - docker run hello-ci-cd
  post_build:
    commands:
      - echo hello post_build!
